openapi: 3.0.0
info:
  version: "1.0.0"
  title: PartyOrganizer
  description: Api for organizing parties
paths:
  /Events:
    get:
      tags:
        - Party
      description: Get list of all events
      operationId: getEvents
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Party'
        '404':
          description: Not Found
    post:
      tags:
        - Party
      summary: Create a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
      responses:
        '201':
          description: Event Succesfully Created
        '400':
          description: Bad Request
  /Events/{event_id}:
    get:
      tags:
        - Party
      description: Get list of all events
      parameters:
        - name: event_id
          in: path
          description: ID of the event to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Party'
        '404':
          description: Not Found
    patch:
      tags:
        - Party
      summary: Update an Party by ID
      parameters:
        - name: event_id
          in: path
          description: ID of the event to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Party'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      tags:
        - Party
      summary: Delete an event by id
      parameters:
        - name: event_id
          in: path
          description: ID of the event to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
  /Events/{event_id}/guests:
    post:
      tags:
        - Guests
      summary: Add a guest to an event
      parameters:
        - name: event_id
          in: path
          description: ID of the event to add a guest to
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guests'
      responses:
        '201':
          description: Guest Successfuly Created
        '400':
          description: Bad Request
        '404':
          description: Not Found
    get:
      tags:
        - Guests
      summary: Get a list of guests for an event
      parameters:
        - name: event_id
          in: path
          description: ID of the event to get guests for
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guests'
        '404':
          description: Not Found
  /Events/{event_id}/guests/{guest_id}:
    get:
      tags:
        - Guests
      summary: Get a guest for an event by ID
      parameters:
        - name: event_id
          in: path
          description: ID of the event to get a guest for
          required: true
          schema:
            type: integer
        - name: guest_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guests'
        '404':
          description: Not Found
    put:
      tags:
        - Guests
      summary: Update a guest for an event by ID
      parameters:
        - name: event_id
          in: path
          description: ID of the event to update a guest for
          required: true
          schema:
            type: integer
        - name: guest_id
          in: path
          description: ID of the guest to update
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guests'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '404':
          description: Not Found
    delete:
      tags:
        - Guests
      summary: Delete a guest for an event by ID
      parameters:
        - name: event_id
          in: path
          description: ID of the event to delete a guest for
          required: true
          schema:
            type: integer
        - name: guest_id
          in: path
          description: ID of the guest to delete
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
components:
  schemas:
    Party:
      type: object
      required:
        - event_id
        - date
        - location
      properties:
        name:
          type: string
          description: The name of the event
        event_id:
          type: integer
          format: int64
          description: The unique identifier for the guest
        date:
          type: string
          format: date
          description: The date of the event
        location:
          type: string
          description: The location of the event
        guest:
          type: array
          items:
            $ref: '#/components/schemas/Guests'
          description: invited guests
        partyDescription:
          type: string
          description: a short text describing the party
    Guests:
      type: object
      required:
        - guest_id
        - name
        - email
      properties:
        guest_id:
          type: integer
          format: int64
          description: The identifier for the guest
        name:
          type: string
          description: The name of the guest
        email:
          type: string
          description: The email address of the guest

tags:
  - description: Description of the event
    name: Party
  - name: Guests
    description: Members invited to an event